### PR TITLE
Fix windows build

### PR DESCRIPTION
**Pull request by louis-bompart**
Replace promise-request by native fetch
Ensure window.onload function is called by executing it if the listener is attached after the document is actually ready

Hope it helps.

### CODE REVIEW

**Comment by louis-bompart** [comment]
Fix #2 as mentioned in its thread.

**Comment by MercerMrc** [comment]
seeing how BrightSchema hasn't been working on this for a while could you possibly provide a build?

**Comment by louis-bompart** [comment]
@MercerMrc sure, I'll create a release on my fork when I'll get home.

**Comment by louis-bompart** [comment]
@MercerMrc https://github.com/louis-bompart/Destiny-2-Discord-Rich-Presence/releases/tag/1.2.1-betaPC

**Comment by MercerMrc** [comment]
Godbless dude. Appreciate the work a lot.

**Comment by MercerMrc** [comment]
Another issue has seem to arise, it connects and loads the player card fine and connects to discord aswell but there's no actual activity shown and this is the error in the console:

```
presence.js:85 Uncaught (in promise) SqliteError {message: "no such table: DestinyActivityDefinition", stack: "SqliteError: no such table: DestinyActivityDefinit…pp.asar/app/presence.js:85:13)↵    at <anonymous>", code: "SQLITE_ERROR"}
pullNewData @ populator.js:60
async function (async)
pullNewData @ populator.js:23
setInterval @ rp_updater.js:27
rp_updater.js:26 Updated presence
presence.js:85 Uncaught (in promise) SqliteError {message: "no such table: DestinyActivityDefinition", stack: "SqliteError: no such table: DestinyActivityDefinit…pp.asar/app/presence.js:85:13)↵    at <anonymous>", code: "SQLITE_ERROR"}
```

**Comment by louis-bompart** [comment]
Nice catch, some path we're not taking into account the user platform and their path separator (i.e. OSX/Unix use / and windows \. Or the opposite, I never know).
Path computing is now platform agnostic.

Fixed 'prerelease' version https://github.com/louis-bompart/Destiny-2-Discord-Rich-Presence/releases/tag/v1.2.2-beta

**Comment by MercerMrc** [comment]
Well for your first question, the player card could easily be removed since it's as easy as looking in-game.
For the second one, consoles don't bother me that much as long as its simple but a UI is always better IMO.

**Comment by louis-bompart** [comment]
👍 thanks for your feedback! Hope this fix it for now :)

**Comment by TrialMacameau** [comment]
Quick question : is the Steam version of the D2 Rich Presence in the work for this fall ?

**Comment by MercerMrc** [comment]
The only thing that'll prolly need to get changed is the account name finder for pc since they are moving away from battlenet but other than that i don't think they'll change anything but we dont really know anything about the new system yet /shrug

**Comment by louis-bompart** [comment]
It's a non issue tbh, because the API allow to get the Bungie Player unique identifier (membershipId) and its platform (membershipType) from a simple call which only require two variables:
the exact username of the player, and a valid API-Key.

We're basing on that on our project.
(In fact, we have already done good progress on this matter, give us your player name and your API key once and we do the rest).

**Comment by TrialMacameau** [comment]
I would but Bungie re-entered maintenance so from my Private API key for the D2 Rich Presence app I can give you this : 1862ab3c1bfd45499059e3c126bd0486
For my ID do you need my Steam or my BNet tag ?

**Comment by louis-bompart** [comment]
@TrialMacameau I'm not sure what you mean/want, and we quite derivated from the topic of this PR, please create an issue in [refactored-happiness](https://github.com/brakacai/refactored-happiness/issues)
(Gotta love those autogenerated repo name from GitHub 😂 )
We can talk more in details there

**Comment by MercerMrc** [comment]
quick thing @louis-bompart the same error from before is still happening now that i've tried it again since the servers are back

```
internal/process/warning.js:18 (node:16196) Warning: N-API is an experimental feature and could change at any time.
writeOut @ internal/process/warning.js:18
presence.js:86 Uncaught (in promise) SqliteError {message: "no such table: DestinyActivityDefinition", stack: "SqliteError: no such table: DestinyActivityDefinit…pp.asar/app/presence.js:86:13)↵    at <anonymous>", code: "SQLITE_ERROR"}
pullNewData @ populator.js:60
rp_updater.js:26 Updated presence
```

**Comment by louis-bompart** [comment]
@MercerMrc I can't reproduce, did you install 1.2.2 ?

**Comment by MercerMrc** [comment]
@louis-bompart Just now did a fresh install after uninstalling and got the same error from before

**Comment by louis-bompart** [comment]
Mh, obv I can't really help with so little informations, can you open the
dev console (Ctrl shift I) and execute step-by-step the loadDb to check it.
Also, I don't think that'll help but clear the electron browser cache by
pressing ctrl-shift-R (hard refresh)

**Comment by MercerMrc** [comment]
deleted the cache and did ctrl-shift-R and started getting new errors(?)

```
internal/process/warning.js:18 (node:10052) Warning: N-API is an experimental feature and could change at any time.
writeOut @ internal/process/warning.js:18
presence.js:86 Uncaught (in promise) SqliteError
rp_updater.js:26 Updated presence
presence.js:19 GET https://www.bungie.net/Platform//Destiny2/null/Profile/null/?components=200 500 ()
get @ presence.js:19
getRecentCharacter @ presence.js:101
pullNewData @ populator.js:24
setInterval @ rp_updater.js:27
presence.js:108 Uncaught (in promise) TypeError: Cannot read property 'characters' of undefined
    at getRecentCharacter (presence.js:108)
    at <anonymous>
getRecentCharacter @ presence.js:108
async function (async)
pullNewData @ populator.js:23
setInterval @ rp_updater.js:27
rp_updater.js:26 Updated presence
presence.js:19 GET https://www.bungie.net/Platform//Destiny2/null/Profile/null/?components=200 500 ()
get @ presence.js:19
getRecentCharacter @ presence.js:101
pullNewData @ populator.js:24
setInterval @ rp_updater.js:27
presence.js:108 Uncaught (in promise) TypeError: Cannot read property 'characters' of undefined
    at getRecentCharacter (presence.js:108)
    at <anonymous>
getRecentCharacter @ presence.js:108
async function (async)
pullNewData @ populator.js:23
setInterval @ rp_updater.js:27
```

**Comment by louis-bompart** [comment]
Did you try closing and opening the program again after that?

**Comment by MercerMrc** [comment]
the ``Cannot read property 'characters'`` error is gone and it has gone back to the ``"no such table: DestinyActivityDefinition"`` error from before

**Comment by louis-bompart** [comment]
Okay, that "worked" as expected.
I'll provide you later today with a 'debug' version with a bunch of logs in
the console.
However if you're able to check step by step what's going on in the
function I mentionned before, that would be great

**Comment by louis-bompart** [comment]
@MercerMrc try this one, https://github.com/louis-bompart/Destiny-2-Discord-Rich-Presence/releases/tag/v1.2.2-beta1.

There should be more non error log but still

**Comment by louis-bompart** [comment]
Major reworks were done to pipe (literally) all this.
https://github.com/louis-bompart/Destiny-2-Discord-Rich-Presence/releases/tag/v1.2.2-beta1.

**Comment by BrightSchema** [comment]
@louis-bompart Much thanks for all the work you did. I actually just rewrote the entire thing, so now all the requests go through my api-gateway so users don't need to make their own api-key.
I didn't actually see this until now (sorry!), but I am going to try to incorporate some of the changes you made during the past few months and ensure a working windows build is available.

**Comment by BrightSchema** [comment]
Added some changes that were still applicable in 3f2eb4b
Closing as it appears the Windows build now works.

**Pull request closed without merging**
